apiVersion: v1
kind: Namespace
metadata:
  name: log-ship

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-ship-deployment
  namespace: log-ship
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-ship
  template:
    metadata:
      labels:
        app: log-ship
    spec:
      containers:
        - name: log-ship-container
          image: ghcr.io/darrylcauldwell/log-shipper:latest
          ports:
            - containerPort: 2049
            - containerPort: 111
            - containerPort: 20048
          securityContext:
            privileged: true
          imagePullPolicy: Always
          volumeMounts:
            - name: nfs-share
              mountPath: /nfs_share
      volumes:
        - name: nfs-share
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: log-ship-service
  namespace: log-ship
spec:
  selector:
    app: log-ship
  ports:
    - name: nfs
      protocol: TCP
      port: 2049
      targetPort: 2049
    - name: rpcbind
      protocol: TCP
      port: 111
      targetPort: 111
    - name: rpcbind-udp
      protocol: UDP
      port: 111
      targetPort: 111
    - name: mountd
      protocol: TCP
      port: 20048
      targetPort: 20048
  type: LoadBalancer
