apiVersion: v1
kind: Namespace
metadata:
  name: log-ship
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/darrylcauldwell/log-shipper:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-ship-deployment
  namespace: log-ship
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-ship
  template:
    metadata:
      labels:
        app: log-ship
    spec:
      containers:
        - name: log-ship-container
          image: ghcr.io/darrylcauldwell/log-shipper:latest
          ports:
            - containerPort: 2049
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: log-ship-service
  namespace: log-ship
spec:
  selector:
    app: log-ship
  ports:
    - protocol: TCP
      port: 2049
      targetPort: 2049
  type: LoadBalancer
  template:
    spec:
      containers:
        - image: ghcr.io/darrylcauldwell/log-shipper:latest