{
 "title": "ECS sample1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "ESXi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Powered ON VMs on ECS Host",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(uuid) (vsphere_vm_sys_uptime_latest)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Datastores on ECS Host",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(lun) (vsphere_host_datastore_read_average)",
     "legendFormat": "{{lun}}"
    }
   ]
  },
  {
   "title": "Top VM by CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sort_desc(vsphere_vm_cpu_usage_average))",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "List of Running VMs (%Avg CPU Usage)",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(vsphere_vm_cpu_usage_average)",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  {
   "title": "Top VM by Mem Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sort_desc(vsphere_vm_mem_usage_average))",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "ESXi CPU usage - Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vsphere_host_cpu_usage_average{cpu=\"instance-total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ESXi CPU Cores usage - History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "targets": [
    { "expr": "vsphere_host_cpu_usage_average", "legendFormat": "{{cpu}}" }
   ]
  },
  {
   "title": "ESXi Mem usage - Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vsphere_host_mem_consumed_average",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ESXi Mem usage - History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "vsphere_host_mem_consumed_average",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "K8s", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }, "repeat": "ecsHost" },
  {
   "title": "Total Amount of Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubernetes_pod_container_cpu_usage_nanocores)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Amount of Volumes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubernetes_pod_volume_used_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Pod by CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sort_desc(kubernetes_pod_container_cpu_usage_nanocores))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "List of Pods",
   "type": "bargauge",
   "gridPos": { "h": 32, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(kubernetes_pod_container_cpu_usage_nanocores) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Top Pod by Mem Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sort_desc(kubernetes_pod_container_memory_usage_bytes))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "K8s Worker Node CPU Usage - Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubernetes_node_cpu_usage_nanocores",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K8s Worker Node CPU usage - History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kubernetes_node_cpu_usage_nanocores",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K8s Worker Node Mem Usage - Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubernetes_node_memory_usage_bytes*100/(kubernetes_node_memory_usage_bytes+kubernetes_node_memory_available_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K8s Worker Node Mem Usage - History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "kubernetes_node_memory_usage_bytes/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K8s Worker Node Storage Usage - Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubernetes_node_fs_used_bytes*100/kubernetes_node_fs_capacity_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K8s Worker Node Storage Usage - History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubernetes_node_fs_capacity_bytes-kubernetes_node_fs_available_bytes",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}