trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - sites/*

pool:
  name: Default
  demands:
    - agent.name -equals Darryls-MacBook-Pro

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: DockerBuildPush
    displayName: 'Docker Build and Push'
    steps:
    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        containerRegistry: 'darrylcauldwell GHCR'
        repository: 'darrylcauldwell/keswick'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest
          $(Build.BuildId)

- stage: Update_QA_Environment
  displayName: 'Update Manchester QA environment'
  jobs:
  - job: UpdateQA
    displayName: 'Updating Manchester QA environment manifest file'
    steps:
    - checkout: self
      persistCredentials: true
    - script: |
        git pull origin main
        yq e '.spec.template.spec.containers[0].image = "ghcr.io/darrylcauldwell/keswick:$(Build.BuildId)"' -i $(Build.SourcesDirectory)/sites/manchester/face-detector.yml
        git add $(Build.SourcesDirectory)/sites/manchester/face-detector.yml
        git commit -m "Update QA manifest ref $(Build.BuildId) [skip ci]"
        git push origin HEAD:main
      displayName: 'Update QA manifest'

- stage: Update_Test_Environment
  displayName: 'Updating Sheffield UAT environment manifest file'
  jobs:
  - job: UpdateUAT
    steps:
    - checkout: self
      persistCredentials: true
    - script: |
        git pull origin main
        yq e '.spec.template.spec.containers[0].image = "ghcr.io/darrylcauldwell/keswick:$(Build.BuildId)"' -i $(Build.SourcesDirectory)/sites/sheffield/face-detector.yml
        git add $(Build.SourcesDirectory)/sites/sheffield/face-detector.yml
        git commit -m "Update UAT manifest ref $(Build.BuildId) [skip ci]"
        git push origin HEAD:main
      displayName: 'Update UAT manifest'

- stage: Update_Prod_Environment
  displayName: 'Update Bakewell production environment manifest file'
  jobs:
  - job: UpdateProd
    steps:
    - checkout: self
      persistCredentials: true
    - script: |
        git pull origin main
        yq e '.spec.template.spec.containers[0].image = "ghcr.io/darrylcauldwell/keswick:$(Build.BuildId)"' -i $(Build.SourcesDirectory)/sites/bakewell/face-detector.yml
        git add $(Build.SourcesDirectory)/sites/bakewell/face-detector.yml
        git commit -m "Update PROD manifest ref $(Build.BuildId) [skip ci]"
        git push origin HEAD:main
      displayName: 'Update PROD manifest'
