trigger:
  - main

pool:
  name: Default
  demands:
    - agent.name -equals Darryls-MacBook-Pro
    
steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'darrylcauldwell GHCR'
      repository: 'darrylcauldwell/keswick'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'


