trigger:
  branches:
    include:
    - main
  paths:
    include:
    - face-detector/*

pool:
  name: Default
  demands:
    - agent.name -equals Darryls-MacBook-Pro

stages:
- stage: Build
  displayName: 'Build and Push Multi-Arch Docker Image'
  jobs:
  - job: DockerBuildPush
    displayName: 'Docker Build and Push'
    variables:
      dockerRegistry: 'ghcr.io'
      imageName: '$(Build.Repository.Name)'
      buildId: '$(Build.BuildId)'
    steps:
    - checkout: self
      displayName: 'Checkout Repository'
    - task: Docker@2
      inputs:
        containerRegistry: 'darrylcauldwell GHCR'
        command: 'login'
    - script: |
        export DOCKER_HOST=unix://$HOME/.docker/run/docker.sock
        docker buildx create --use --name mybuilder
        docker buildx inspect --bootstrap
      displayName: 'Set up Docker Buildx'
    - script: |
        cd face-detector
        docker buildx build --platform linux/amd64,linux/arm64 \
          -t $(dockerRegistry)/$(imageName):latest \
          -t $(dockerRegistry)/$(imageName):$(buildId) \
          --push .
      displayName: 'Build and push multi-arch image'
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
    - script: |
        docker buildx imagetools inspect $(dockerRegistry)/$(imageName):latest
        docker buildx imagetools inspect $(dockerRegistry)/$(imageName):$(buildId)
      displayName: 'Inspect multi-arch images'

- stage: Update_QA_Environment
  displayName: 'Update Manchester QA environment'
  jobs:
  - job: UpdateQA
    displayName: 'Manchester QA'
    steps:
    - checkout: self
      persistCredentials: true
    - script: |
        git pull origin main
        yq e '.spec.template.spec.containers[0].image = "ghcr.io/darrylcauldwell/keswick:$(Build.BuildId)"' -i $(Build.SourcesDirectory)/sites/manchester/face-detector.yml
        git add $(Build.SourcesDirectory)/sites/manchester/face-detector.yml
        git commit -m "Update QA manifest ref $(Build.BuildId) [skip ci]"
        git push origin HEAD:main
      displayName: 'Update QA manifest'

- stage: Approve_QA_Update
  displayName: 'Approve QA Update'
  jobs:
  - job: ApproveQA
    pool: server
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # Task times out in 1 day
      inputs:
        notifyUsers: |
          darryl.cauldwell@gmail.com
        instructions: 'Please validate the build has passed QA and can be rolled out to UAT.'
        onTimeout: 'reject'

- stage: Update_Test_Environment
  displayName: 'Sheffield UAT'
  jobs:
  - job: UpdateUAT
    steps:
    - checkout: self
      persistCredentials: true
    - script: |
        git pull origin main
        yq e '.spec.template.spec.containers[0].image = "ghcr.io/darrylcauldwell/keswick:$(Build.BuildId)"' -i $(Build.SourcesDirectory)/sites/sheffield/face-detector.yml
        git add $(Build.SourcesDirectory)/sites/sheffield/face-detector.yml
        git commit -m "Update UAT manifest ref $(Build.BuildId) [skip ci]"
        git push origin HEAD:main
      displayName: 'Update UAT manifest'

- stage: Approve_UAT_Update
  displayName: 'Approve UAT Update'
  jobs:
  - job: ApproveUAT
    pool: server
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # Task times out in 1 day
      inputs:
        notifyUsers: |
          darryl.cauldwell@gmail.com
        instructions: 'Please validate the build has passed UAT and can be rolled out to production.'
        onTimeout: 'reject'

- stage: Update_Prod_Environment
  displayName: 'Bakewell PROD'
  jobs:
  - job: UpdateProd
    steps:
    - checkout: self
      persistCredentials: true
    - script: |
        git pull origin main
        yq e '.spec.template.spec.containers[0].image = "ghcr.io/darrylcauldwell/keswick:$(Build.BuildId)"' -i $(Build.SourcesDirectory)/sites/bakewell/face-detector.yml
        git add $(Build.SourcesDirectory)/sites/bakewell/face-detector.yml
        git commit -m "Update PROD manifest ref $(Build.BuildId) [skip ci]"
        git push origin HEAD:main
      displayName: 'Update PROD manifest'
