# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: 'ghcr.io/darrylcauldwell/face-detector:latest, ghcr.io/darrylcauldwell/face-detector:pipeline'

stages:
- stage: Build
  displayName: Buildimage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Buildimage
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/face-detector/Dockerfile'
        tags: |
          $(tag)