trigger:
- main

resources:
- repo: self

variables:
  tag: 'ghcr.io/darrylcauldwell/face-detector:latest,ghcr.io/darrylcauldwell/face-detector:pipeline'

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: build
    dockerfile: '$(Build.SourcesDirectory)/face-detector/Dockerfile'
    tags: |
      $(tag)