trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - sites/*

pool:
  name: Default
  demands:
    - agent.name -equals Darryls-MacBook-Pro

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: DockerBuildPush
    displayName: 'Docker Build and Push'
    steps:
    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        containerRegistry: 'darrylcauldwell GHCR'
        repository: 'darrylcauldwell/keswick'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest
          $(Build.BuildId)

- stage: Update_QA_Environment
  displayName: 'Update Manchester QA environment'
  jobs:
  - job: UpdateQA
    displayName: 'Manchester QA'
    steps:
    - checkout: self
      persistCredentials: true
    - script: |
        git pull origin main
        yq e '.spec.template.spec.containers[0].image = "ghcr.io/darrylcauldwell/keswick:$(Build.BuildId)"' -i $(Build.SourcesDirectory)/sites/manchester/face-detector.yml
        git add $(Build.SourcesDirectory)/sites/manchester/face-detector.yml
        git commit -m "Update QA manifest ref $(Build.BuildId) [skip ci]"
        git push origin HEAD:main
      displayName: 'Update QA manifest'

- stage: Approve_QA_Update
  displayName: 'Approve QA Update'
  jobs:
  - job: ApproveQA
    pool: server
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # Task times out in 1 day
      inputs:
        notifyUsers: |
          darryl.cauldwell@gmail.com
        instructions: 'Please validate the build has passed QA and can be rolled out to UAT.'
        onTimeout: 'reject'

- stage: Update_Test_Environment
  displayName: 'Sheffield UAT'
  jobs:
  - job: UpdateUAT
    steps:
    - checkout: self
      persistCredentials: true
    - script: |
        git pull origin main
        yq e '.spec.template.spec.containers[0].image = "ghcr.io/darrylcauldwell/keswick:$(Build.BuildId)"' -i $(Build.SourcesDirectory)/sites/sheffield/face-detector.yml
        git add $(Build.SourcesDirectory)/sites/sheffield/face-detector.yml
        git commit -m "Update UAT manifest ref $(Build.BuildId) [skip ci]"
        git push origin HEAD:main
      displayName: 'Update UAT manifest'

- stage: Approve_UAT_Update
  displayName: 'Approve UAT Update'
  jobs:
  - job: ApproveUAT
    pool: server
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # Task times out in 1 day
      inputs:
        notifyUsers: |
          darryl.cauldwell@gmail.com
        instructions: 'Please validate the build has passed UAT and can be rolled out to production.'
        onTimeout: 'reject'

- stage: Update_Prod_Environment
  displayName: 'Bakewell PROD'
  jobs:
  - job: UpdateProd
    steps:
    - checkout: self
      persistCredentials: true
    - script: |
        git pull origin main
        yq e '.spec.template.spec.containers[0].image = "ghcr.io/darrylcauldwell/keswick:$(Build.BuildId)"' -i $(Build.SourcesDirectory)/sites/bakewell/face-detector.yml
        git add $(Build.SourcesDirectory)/sites/bakewell/face-detector.yml
        git commit -m "Update PROD manifest ref $(Build.BuildId) [skip ci]"
        git push origin HEAD:main
      displayName: 'Update PROD manifest'
