apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: rtos
spec:
  hardware:
    cpus: 4
    memory: 8Gi
  policies:
    resources:
      requests:
        cpu: 4
        memory: 8Gi
  configSpec:
    _typeName: VirtualMachineConfigSpec
    latencySensitivity:
      _typeName: LatencySensitivity 
      level: high
    flags:
      _typeName: VirtualMachineFlagInfo
      enableLogging: false
    extraConfig:
      - _typeName: OptionValue
        key: "sched.mem.lpage.enable1GPage"
        value: "true"
      - _typeName: OptionValue
        key: "sched.cpu.affinity.exclusiveNoStats"
        value: "true" 
      - _typeName: OptionValue
        key: "monitor.forceEnableMPTI"
        value: "true"
      - _typeName: OptionValue
        key: "timeTracker.lowLatency"
        value: "true"
      - _typeName: OptionValue
        key: "sched.qos.l3.monitor"
        value: "true"
      - _typeName: OptionValue
        key: "sched.qos.l3.sizeKB"
        value: "4096"
