---
apiVersion: v1
kind: Namespace
metadata:
  name: edge-llm

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-llm
  namespace: edge-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-llm
  template:
    metadata:
      labels:
        app: edge-llm
    spec:
      containers:
      - name: edge-llm
        image: edge-llm:latest
        ports:
        - containerPort: 11434
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: edge-llm-service
  namespace: edge-llm
spec:
  type: LoadBalancer
  selector:
    app: edge-llm
  ports:
  - port: 80
    targetPort: 8080
    name: webui
  - port: 11434
    targetPort: 11434
    name: ollama
